name: ${project.name}
main: de.themoep.resourcepacksplugin.bukkit.WorldResourcepacks
version: '${minecraft.plugin.version}'
author: Phoenix616
softdepend: [ViaVersion, ProtocolSupport, Geyser-Spigot, floodgate, AuthMe, OpeNLogin, nLogin]
api-version: 1.13
commands:
   wrp:
      aliases: [worldresourcepacks]
      description: Main plugin command.
      usage: /<command> [addpack|pack|listassignments|assignment|deleteassignment|globalassignment|generatehashes|reload [resend]|version]
      permission: worldresourcepacks.command
      permission-message: You don't have the permission <permission>
   usepack:
      description: Command for setting the pack of a player.
      usage: /<command> <packname> [<playername>] [<temp>]
      permission: worldresourcepacks.command.usepack
      permission-message: You don't have the permission <permission>
   resetpack:
      description: Command for resetting the pack of a player.
      usage: /<command> [<playername>] [<temp>]
      permission: worldresourcepacks.command.resetpack
      permission-message: You don't have the permission <permission>
permissions:
   worldresourcepacks.command:
      description: Gives permission to use the command
      default: op
   worldresourcepacks.command.usepack:
      description: Gives permission to set ones pack
      default: op
   worldresourcepacks.command.usepack.others:
      description: Gives permission to set the pack of other players
      default: op
   worldresourcepacks.command.usepack.temporary:
      description: Gives permission to set whether or not the pack should only be temporary set and not stored
      default: op
   worldresourcepacks.command.resetpack:
      description: Gives permission to reset ones pack
      default: op
   worldresourcepacks.command.resetpack.others:
      description: Gives permission to reset the pack of other players
      default: op
   worldresourcepacks.command.resetpack.temporary:
      description: Gives permission to reset whether or not the pack should only be temporary reset and not stored
      default: op
   worldresourcepacks.command.generatehashes:
      description: Gives permission to (re-)generate the sha1 hashes of the packs
      default: op
   worldresourcepacks.command.version:
      description: Gives permission to see the plugin's version
      default: op
   worldresourcepacks.command.reload:
      description: Gives permission to reload the plugin
      default: op